### ISSUE TITLE
User evaluation: apfs-clone-checker seems to work correctly on macOS 11 Big Sur

### ISSUE THREAD

**Issue by porg** [dyorgio/apfs-clone-checker#1]
Testing whether clone_checker works correctly within a controlled environment
- APFS Clone Checker - Version: 1.0.0.0
- macOS Big Sur 11.2.1

```
$ cd ~/Documents/Tests/copying-on-APFS
$ ls -l
-rw-r--r--@ 1 myUserName  staff  71632724 Feb 18 11:10 1-original.mov
-rw-r--r--@ 1 myUserName  staff  71632724 Feb 18 11:10 2-copy-on-same-APFS-volume.mov
-rw-r--r--@ 1 myUserName  staff  71632724 Feb 18 11:10 3-copy-via-external-APFS-volume.mov
# All files have a link count number of 1.
# This prooves that the duplication/copy operations were not achieved via hardlinking.

$ sha1sum *
sameCheckSum  1-original.mov
sameCheckSum  2-copy-on-same-APFS-volume.mov
sameCheckSum  3-copy-via-external-APFS-volume.mov
# Checksum tool shows that all files indeed had the same content.

$ clone_checker 1-original.mov 2-copy-on-same-APFS-volume.mov
1 # Indeed a copy-on-write clone!
$ clone_checker 1-original.mov 3-copy-via-external-APFS-volume.mov 
0 # Not as copy-on-write clone as it had travelled through another APFS volume.
  # Which was even on another physical device to be absolutely sure.
```

**Conclusion**: clone_checker seems reliable to me from these tests!

**Comment by porg** [comment]
@dyorgio 
Thanks to you as the project creator / owner for providing this software.
Leaving this open in order for you to comment if you want and finally close if all good!
My use case which lead me here is documented in #2.

**Comment by porg** [comment]
@all One more hint on unsigned binary executables in macOS Big Sur like this one:
1.  When downloading the compiled binary and adding it manually into i.e. `~/bin/`
2. Run this once in Finder and there say OK to the security/privacy dialog.
3. From then on you can execute it hassle-free from within Terminal. Before that I had permission issues.

**Comment by dyorgio** [comment]
Hi @porg, tks for your tests!
Nice to know that it is working outside my machine 😄
