### ISSUE TITLE
Failes when in place compression is involved

### ISSUE THREAD

**Issue by kapitainsky** [dyorgio/apfs-clone-checker#8]
Nice tool but can't handle sitution when clone involved in place compressed files, then it displays:

"Cannot convert logical to physical offset. 45 Operation not supported"

error message

**Comment by kapitainsky** [comment]
The way to reproduce:

HFS+/APFS filesystem
compress file1 using e.g. https://github.com/RJVB/afsctool

`afsctool -c file1`

clone it:

`cp -c file1 file2`

try to use apfs-clone-checker on both files

**Comment by dyorgio** [comment]
Hi @kapitainsky, appears that it is a limitation of F_LOG2PHYS/F_LOG2PHYS_EXT.

In my search I found the cause: Blocks of compressed files sometimes are in memory (not on physical device).

So, at moment, no support to compressed files 😞 .
